"""List of users who, from manual QA, might've just been spamming, so might
want to consider removing their data.

List generated by going through the user engagement metrics (e.g., likes) and
flagging any suspicious activity (e.g., only active during the course of the
study, only a few followers, no posts but only a few reposts, and thousands
of likes for a single user).
"""

excludelist_handles = [
    "willlam20.bsky.social",
    "georgina00.bsky.social",
    "mharry03.bsky.social",
    "jakesdaniel1990.bsky.social",
    "jaydenjakes1987.bsky.social",
    "matthewvivian2003.bsky.social",
]
