# Example job configuration for the distributed job coordination system
name: example-data-processing-job
description: Example job that demonstrates the distributed processing capabilities

# Input configuration
input:
  path: ./data/example.csv
  file_pattern: "*.csv"
  format: csv

# Algorithm configuration
algorithm:
  name: text_classification
  params:
    model_name: bert-base-uncased
    threshold: 0.75
    max_length: 256
    batch_size: 32

# Compute resource configuration
compute:
  min_workers: 2
  max_workers: 5
  cpu_per_worker: 2
  memory_per_worker: 4Gi
  gpu_per_worker: 0

# Output configuration
output:
  path: ./results/example_output/
  format: json
  compression: none
  overwrite: true

# Notification configuration
notification:
  on_completion: true
  on_failure: true
  email: user@example.com
  webhook: https://example.com/webhook

# Advanced configuration
advanced:
  batch_size: 100
  max_retries: 3
  timeout_seconds: 3600
  priority: medium 