# IME feature configuration
feature_type: "ime"
columns:
  - "prob_affinity"
  - "prob_compassion"
  - "prob_constructive"
  - "prob_curiosity"
  - "prob_nuance"
  - "prob_personal_story"
  - "prob_reasoning"
  - "prob_respect"
threshold: 0.5
description: "IME (Interpersonal Meaning Extraction) content classification features"
