# Political feature configuration
feature_type: "political"
columns:
  - "is_sociopolitical"
  - "political_ideology_label"
threshold: 0.5
description: "Political content classification features"
ideologies:
  - "left"
  - "right"
  - "moderate"
