# Data Loader Configuration for Topic Modeling Pipeline
# 
# This configuration file defines the settings for different data loader types
# in the topic modeling pipeline. All data is assumed to be stored in .parquet format.
#
# Author: AI Agent implementing MET-44
# Date: 2025-01-20

data_loader:
  # Default data loader type
  type: "local"
  
  # Local data loader configuration
  local:
    enabled: true
    service: "preprocessed_posts"  # Service name for local data loading
    directory: "cache"            # Directory to load from: "active" or "cache"
  
  # Production data loader configuration (for future use)
  production:
    enabled: false
    endpoint: ""                  # API endpoint for production data
    api_key: ""                   # API key for authentication
    timeout: 30                   # Request timeout in seconds

# Data validation settings
validation:
  max_date_range_days: 365        # Maximum date range to allow
  min_text_length: 10            # Minimum text length for posts
  max_text_length: 10000         # Maximum text length for posts

# Performance and optimization settings
performance:
  batch_size: 1000               # Batch size for data processing
  memory_limit_gb: 8             # Memory limit for data loading
  enable_compression: true       # Enable data compression for large datasets
