global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      group_wait: 0s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'slack-warning'
      group_wait: 30s
      repeat_interval: 1h
    - match:
        severity: info
      receiver: 'slack-info'
      group_wait: 5m
      repeat_interval: 4h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#redis-monitoring'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.grafana_url" . }}'
          - type: button
            text: 'View in Alertmanager'
            url: '{{ template "slack.alertmanager_url" . }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#redis-monitoring'
        send_resolved: true
        title: '🚨 {{ template "slack.title" . }}'
        text: '{{ template "slack.critical.text" . }}'
        color: 'danger'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.grafana_url" . }}'
          - type: button
            text: 'Acknowledge'
            url: '{{ template "slack.acknowledge_url" . }}'

  - name: 'slack-warning'
    slack_configs:
      - channel: '#redis-monitoring'
        send_resolved: true
        title: '⚠️ {{ template "slack.title" . }}'
        text: '{{ template "slack.warning.text" . }}'
        color: 'warning'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.grafana_url" . }}'

  - name: 'slack-info'
    slack_configs:
      - channel: '#redis-monitoring'
        send_resolved: true
        title: 'ℹ️ {{ template "slack.title" . }}'
        text: '{{ template "slack.info.text" . }}'
        color: 'good'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.grafana_url" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'
