"""Helper functions for classification models."""
DEFAULT_INFERENCE_FIELDS = [
    "TOXICITY", "AFFINITY_EXPERIMENTAL", "COMPASSION_EXPERIMENTAL",
    "CONSTRUCTIVE_EXPERIMENTAL", "CURIOSITY_EXPERIMENTAL", "NUANCE_EXPERIMENTAL", # noqa
    "PERSONAL_STORY_EXPERIMENTAL", "ALIENATION_EXPERIMENTAL", "FEARMONGERING_EXPERIMENTAL", # noqa
    "GENERALIZATION_EXPERIMENTAL", "MORAL_OUTRAGE_EXPERIMENTAL", "POWER_APPEAL_EXPERIMENTAL", # noqa
    "SCAPEGOATING_EXPERIMENTAL"
]
