backfill:
  name: "backfill_study_users"
  version: "1.0"
  source:
    type: "sqlite"
    path: "/api/backfill_router/backfill_study_users/backfill_study_users.sqlite",
  record_types:
    - "app.bsky.feed.post"
    - "app.bsky.feed.like"
    - "app.bsky.feed.repost"
  time_range:
    start_date: "2025-01-01"
    end_date: "2025-02-01"
  storage:
    type: "dynamodb"
    table_name: "backfill_study_users_results"
    region: "us-east-1" 
  