backfill:
  name: "backfill_posts_liked_by_study_users"
  version: "1.0"
  source:
    type: "sqlite"
    path: "api/backfill_router/backfill_posts_engaged_with_by_study_users/backfill_posts_liked_by_study_users.sqlite"
    query: null  # Not used for S3
  record_types:
    - "app.bsky.feed.like"
    - "app.bsky.feed.post"
  time_range:
    start_date: "2025-01-01"
    end_date: "2025-02-01"
  storage:
    type: "dynamodb"
    table_name: "backfill_posts_liked_by_study_users_results"
    region: "us-east-1"