PREFIXES_TO_MIGRATE = [
    "daily_superposters/cache",
    "feeds",
    "fetch_posts_used_in_feeds",
    "generated_feeds",
    "generated_user_session_logs",
    "in_network_user_activity",
    "ml_inference_ime/active",
    "ml_inference_ime/cache",
    "ml_inference_perspective_api/active",
    "ml_inference_perspective_api/cache",
    "ml_inference_sociopolitical/active",
    "ml_inference_sociopolitical/cache",
    "ml_inference_valence_classifier/active",
    "ml_inference_valence_classifier/cache",
    "post_scores/active",
    "post_scores/cache",
    "preprocessed_posts/firehose/cache",
    "preprocessed_posts/most_liked/cache",
    "study_user_activity/create/block/active",
    "study_user_activity/create/block/cache",
    "study_user_activity/create/follow/active",
    "study_user_activity/create/follow/cache",
    "study_user_activity/create/like/active",
    "study_user_activity/create/like/cache",
    "study_user_activity/create/post/active",
    "study_user_activity/create/post/cache",
    "study_user_activity/create/reply/active",
    "study_user_activity/create/reply/cache",
    "study_user_activity/create/repost/active",
    "study_user_activity/create/repost/cache",
    "user_session_logs/active",
    "user_session_logs/cache",
]

DEFAULT_S3_ROOT_PREFIX = "bluesky_research/2024_nature_paper_study_data"
