WRITE_DOCS_PROMPT = """
    You are an expert documentation writer. You are given a code file and
    a description of the code. You need to write the documentation for the code.

    The code is typically handled, at the top level, with a main.py or a
    handler.py file. From there, follow the track of the imports in the code
    to find the other files that are used in the code.

    Explain step-by-step, using numbered steps and Markdown formatting, the
    logic of the microservice. Structure in the following format:

    <Service Title>

    <High-level overview of the service>

    <Detailed explanation of the code>
        - Do so in steps. The functions have detailed docstrings. Each
        function is designed in a composable way, so you can follow the
        logic of the code by following the layering and composition of the
        functions.

    <Testing details>
        - Tests are typically detailed in a "tests/" directory. Note the
        location of the tests for the given code. Then review the docstrings
        of the files in the "tests/" directory to understand what is tested.
        Then, in bullet points, outline (1) the name of the test file and
        which file is being tested, and then in sub-bullets, outline the tests 
        that are being done.

    """


REWRITE_DOCSTRING_PROMPT = """
    You are an expert technical documentation writer and a staff software engineer,
    an expert in high-impact, high-quality software development at scale.
    Review the docstring in <file> and describe if the docstring matches the
    inputs and expected functionality in the code itself. Assume that in cases
    of conflict, the code implementation takes precedence over the docstring.
    Rewrite the docstring details to be more accurate and detailed. Then
    describe in detail the reason for any changes made to the docstring. Your
    docstrings are expected to have (1) the args for the function (with typing),
    (2) the expected outputs, and (3) the expected behavior, in step-by-step detail
    as described by the control flow of the code.

    Some notes:
    - Any timestamps, unless otherwise indicated, should be assumed to take
    the "timestamp_format = "%Y-%m-%d-%H:%M:%S"" defined in lib/constants.py.
    - Any partition dates should be assumed to take the "partition_date_format =
    "%Y-%m-%d" defined in lib/constants.py.
    - Remove redundancy in the docstring and add precise details of the inputs,
    outputs, and behavior.
    - Follow type hints provided in the code.
    - At the end of your response, provide a [Suggestions] section where you
    suggest improvements to the code (if any) to improve the following details
    of either the code or the docstring:
        - Clarity of the code
        - Completeness of the code
        - Performance of the code
        - Readability of the code
        - Maintainability of the code
        - Error handling
    - If there are no suggestions, state that there are no suggestions.
    - If there are no changes to the docstring, state that there are no changes
    to the docstring.
    - Also at the end of your response, provide a [Clarifications] section where
    you ask questions for cases where the code or implementation details are
    unclear. This could look something like:
        - The function is called with a payload. What is the payload?
        - What is the service that uses this function?
        - There are missing type hints or the type hints seem inconsistent with how
        the function is used or how the control flow of the code is implemented
        (e.g., the function returns a dict but we try to access it like a list).
        - What is the expected behavior of the function?
        - What is the expected output of the function?
"""


COMMIT_MESSAGE_PROMPT = """
    Write a commit message for the changes made to the code in <file>.
    The commit message should be in the present tense, and should be no more
    than 50 characters. Append with " (via Composer LLM)" to indicate that the
    commit message was generated by the Composer LLM.

    I want these types of commit messages:
    - (feat): A new feature was added.
    - (fix): A bug was fixed.
    - (refactor): The code was refactored.
    - (test): A test was added or modified.
    - (docs): The documentation was updated.
    - (chore): Miscellaneous changes.

    The commit message should be formatted as follows:
    [type] <description> (via Composer LLM)
"""
