_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
