version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=default # OK since it is local.
    volumes:
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/default-dashboard.json
    restart: unless-stopped
